### ISSUE TITLE
External player issue

### ISSUE THREAD

**Issue by testman42** [Perflyst/Twire#102]
When selecting "Use external player" the message "Failed to send URL to external player".
I am using VLC as external player (for the purpose of #99 )
LineageOS 16 is the OS that I am using.

How would I get more information about what is going on when attempting to open external player?

**Comment by seanlaguna** [comment]
This happens to me only with VODs, live streams work fine.

By the way I use this app primarily for the external player feature because VLC has the best casting capabilities of any Android video player I've found. You can cast Twitch to your smart TV without it playing on your phone at all, keeping your phone completely free for any other use. Pretty awesome.
