### ISSUE TITLE
Wrong aspect ratio and strange interaction with side chat in landscape

### ISSUE THREAD

**Issue by atomizer** [Perflyst/Twire#66]
- Twire 1.9.8
- phone: Xiaomi Mi 8 (Snapdragon 845, Adreno 630)
- Android 9 (Lineage 16)
- screen: 2248x1080 with a notch on top and round corners on the bottom

Default landscape view, the video is in wrong aspect ratio - 2.08:1 (same as the whole screen), has top & bottom black bars:
![](https://user-images.githubusercontent.com/418303/70395315-769bae80-1a0e-11ea-8252-d3a6c7fed984.png)

After pulling out the side chat, aspect ratio is still wrong:
![](https://user-images.githubusercontent.com/418303/70395352-d2fece00-1a0e-11ea-824e-dccaed24dfeb.png)

Closing the side chat, aspect ratio still the same, but the video now fills full height, cutting off on the right:
![](https://user-images.githubusercontent.com/418303/70395409-4d2f5280-1a0f-11ea-9496-4e5637d7fcf9.png)

Probably related to #56.

**Comment by saasasasasa** [comment]
[1.9.8] I have a phone with 18:9 aspect ratio screen and streams with 16:9 ratio are stretched sideways.

**Comment by samfun123** [comment]
@atomizer I believe the issue was related to the fact that Xiaomi Mi 8 has notches which Twire didn't account for when calculating the size of the screen. Hopefully it'll be fixed when you test out the next version.

@saasasasasa I don't know if your phone had notches but if the issue isn't fixed in the next version, open a new issue with details like what phone you're using and I'll look into it.

**Comment by saasasasasa** [comment]
Aspect ratio for me is now fine with version 1.9.9.
