### ISSUE TITLE
Logging into account goes to Twitch's landing page

### ISSUE THREAD

**Issue by digital-mystik** [Perflyst/Twire#78]
Just noticed today that I can no longer log into Twire since it now forwards to Twitch via the internal browser.

**Comment by LukasThyWalls** [comment]
It also happens to me.

I logged again because this https://github.com/SebastianRask/Pocket-Plays-for-Twitch/issues/29 which is doing that in Pocket Plays and also Twire since yesterday, but yesterday, Twire says it's logged and fetches the followed channels, when today it goes to the Twitch mobile front page and nothing more, because you need to close Twire when it's in the Twitch front page, ~~and if you go again you are logged but there aren't followed channels~~. Edit: I just closed and enter Twire a few times and then my followed channels appeared.
 
The "Servers not responding" happened since yesterday always, when you see the "My Streams" tab.

But if you search a channel and want to see a VOD or a Top Stream, or everything else, it seems to work, with chat available. You just can't see the Lives for your followed channels, because the "My Streams" tab doesn't show anything.

Thanks.

**Comment by SebastianRask** [comment]
The "Servers not responding" issue is caused by a change to the /streams/followed endpoint. Twitch decided to remove the "total" property from the response. The app is using this property to decide if additional requests are needed when scrolling. 

You can look into this [commit ](https://github.com/SebastianRask/Pocket-Plays-for-Twitch/commit/d4e04e8015120ff3f30382c99ace8fe03d9de4c6) to see how I fixed it.

**Comment by SebastianRask** [comment]
The Twitch landing page log-in issue might be caused by your use of localhost as redirect url in the `LOGIN_URL` in `LoginActivity.java`. Does this match your URL in the registered Twitch application? @Perflyst

**Comment by Perflyst** [comment]
Yes, the url is set to `http://localhost/oauth_authorizing` in the twitch application

**Comment by digital-mystik** [comment]
A commit was made for a similar issue upstream: https://github.com/SebastianRask/Pocket-Plays-for-Twitch/commit/d4e04e8015120ff3f30382c99ace8fe03d9de4c6

**Comment by Perflyst** [comment]
I already ported the commit 7d6d639291bd1f98965bce5a608747f74d57f096 and released a new version. But the initial issue is a different one.

**Comment by kuremu** [comment]
I'm getting this issue on 2.0.0 from F-Droid

**Comment by frenchieisverige** [comment]
Me too, with version 1.9.9

**Comment by LukasThyWalls** [comment]
It was working fine with 2.0.0 for me but reading the comments i did some test.

When i installed 2.0.0, Twire was logged and everything was working fine. I tried to logout and login again, and now i can be logged anymore, because as the original issue, it shows the Twitch frontpage (with my followed channels) and my only options is go back or exit the app, but in any case i ended not being logged with my account, as it does with 1.9.9. I tried several times with the two login access (directly in the menu, and inside Settings -> General) with the same result.

**Comment by HichamBI** [comment]
Hello,
Same issue here with thel last version from f-droid.

**Comment by samfun123** [comment]
I included an more detailed explanation in my commit but basically what was happening is that Twitch was doing some weird redirecting that caused us to display www.twitch.tv/login. Which is why it then went to the landing page because that's where you get sent to after logging into Twitch normally.

**Comment by LukasThyWalls** [comment]
10 days since the fix but no new version released? Is there any problem to release it?

**Comment by Perflyst** [comment]
There is not, I will release a new version now

**Comment by Perflyst** [comment]
There we go https://github.com/Perflyst/Twire/releases/tag/v2.0.1 - F-Droid should catch up in a few days as usual

**Comment by LukasThyWalls** [comment]
Thanks Perflyst! As anyone can't login with the old version, i need to point out to do a new release if it's possible.
