### ISSUE TITLE
[Bug] "Twitch servers don't seem to be responding"

### ISSUE THREAD

**Issue by tycrek** [Perflyst/Twire#84]
I get email notifications from Twitch when someone I follow starts streaming. I open the app, which I have set to open to My Streams, and after a few seconds of loading it stops, and triggers a toast message:

> "Oops, Twitch's servers don't seem to be responding. Refresh?"

At which point I refresh and the same thing happens. The only way to actually start viewing the stream is to go to Search and look up the streamer. This is in addition to issue #83 which I also opened, not sure if they are related.

**Comment by samfun123** [comment]
First of all make sure you're on the latest version of the app because I believe there was a bug fixed about this recently.
Second, could you try logging out and then back in on the app? I suspect there's something weird happening where Twitch is revoking your login after a long time and logging in again would fix it.

**Comment by tycrek** [comment]
@samfun123 I have the latest F-Droid version installed. I can try logging out, once someone I follow starts streaming I'll try to watch and report back here.

**Comment by tycrek** [comment]
Logging out and back in worked for me. Thanks for the help!

**Comment by k1gen** [comment]
Same issue, but in Followed streamers tab and logging out and back in didn't work
